[WIP] Port unique users to use Analytics server
avantifellows/plio-frontend pull request #225
Opened 2021-05-06 13:03 UTC by dalmia

Fixes #224 

## Summary
- [ ] replace unique users to come from Plio Analytics server instead of backend
- [x] Updated environment variables for the Plio Analytics server
- [x] Updated `docs/ENV.md` to add explanations for new env variables

## Test Plan
TODO

2021-05-07 04:25 UTC, deepansh96 requested changes

2021-05-07 04:25 UTC, deepansh96 commented on src/services/API/RootClient.js
> +// analytics API
```suggestion
// analytics API client
```

2021-05-07 04:25 UTC, deepansh96 commented on src/services/API/Plio.js
> +    };
I think it's best to encapsulate this query and all the queries that we will use soon in a separate file and import them here. Just like we've done for endpoints and API calls.
A query directory can have different files like Users, Session, Plios etc and each file will have the related query in a variable or const

2021-05-07 04:25 UTC, deepansh96 commented on src/services/API/Plio.js
> +    };
Before this cube js change, we were querying the plio ka endpoint to get this metric. But here we're querying sessions ka cube, why is that? can't it be done by querying the plio ka cube?

2021-05-07 04:57 UTC, dalmia commented on docs/ENV.md
> +Auth token for the analytics REST API - can be empty for local development.
Yes

2021-05-07 04:57 UTC, dalmia commented on src/services/API/Endpoints.js
> +  listPliosEndpoint = "list_uuid/",
Not how it was being used earlier.

2021-05-07 09:32 UTC, deepansh96 commented on src/services/API/Queries/Plio.js
> +  // converted to SQL by CubeJS: https://cube.dev/docs/getting-started-cubejs-schema
Do we really need this?
`this is the query in the CubeJS Data Schema which is automatically converted to SQL by CubeJS`
Can keep the link for reference purposes

2021-05-07 09:32 UTC, deepansh96 commented on src/services/API/Plio.js
> +import { uniqueUsersQuery } from "./Queries/Plio.js";
`import { uniqueUsersQuery } from "@/services/API/Queries/Plio.js";`

2021-05-12 08:53 UTC, dalmia commented on src/services/API/Analytics.js
> +      "/cubejs-token",
should be in the endpoints file

2021-05-12 08:56 UTC, dalmia commented on src/store/modules/auth.js
> +  setAnalyticsAccessToken(state, accessToken) {
don't we need an unset method that we might need when we have to refresh the token?

2021-05-12 08:57 UTC, dalmia commented on src/services/API/Analytics.js
> +  async getAnalyticsAccessToken() {
one line comment.

2021-05-12 19:11 UTC, merged