Removes support for plio-analytics
avantifellows/plio-frontend pull request #595
Opened 2022-01-21 20:16 UTC by dalmia

Fixes #{issue id}

## Summary

## Test Plan

- [ ] Test Responsiveness
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- [ ] Cross-Browser Testing
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari (use BrowserStack)
- [ ] Local Language Support
- [ ] Hygiene and Housekeeping
   - [ ] Self-review
   - [ ] Comments have been added appropriately
   - [ ] Check for bundle size [here](https://bundlephobia.com/) if adding a package
   - [ ] Added relevant details like Labels/Projects/Milestones etc.
   - [ ] If adding or removing any environment variable:
       - [ ] update `docs/ENV.md`
       - [ ] update Github Workflow files
       - [ ] update DockerFile
       - [ ] update the secrets for staging and production
- [ ] Testing
   - [ ] Wrote tests
   - [ ] Tested locally
   - [ ] Tested on staging
   - [ ] Tested on an actual physical phone
   - [ ] Tested on production
- [ ] Lighthouse Checks
   - [ ] Images have `alt` attributes
   - [ ] Any `<img>` tags have `width` and `height` specified
   - [ ] Any `target="_blank"` links have `rel="noopener"`
   - [ ] Only SVGs are used as images. If PNGs are used, their size has been optimised.
   - [ ] Any SVGs without text have their `aria-label` attributes set

2022-01-26 10:02 UTC, deepansh96 requested changes

2022-01-26 10:02 UTC, deepansh96 commented
- When I switch workspace, when the plios are loading for the home page, for half a second the Untitled title shows along with an empty badge. Ideally it should keep showing the skeleton until all data has been loaded and only remove the skeleton when everything is present. This doesn't happen when I come on the home page but only while switching workspace.
- Also, I know no one will do this, but while this loading part, when the Untitiled and empty badge comes up, if I very quickly click edit, it throws an error because the plioId is not available.
https://user-images.githubusercontent.com/20169829/151124769-51c29f5f-ea6b-4556-a82d-9bca18121983.mov


- Maybe we should give some kind of information as to what does "-" mean on an analytics value
![image](https://user-images.githubusercontent.com/20169829/151136914-3c52e7c1-f10d-4ea9-bd77-3cc91137bc14.png)

2022-01-26 14:47 UTC, deepansh96 commented
Reminder - When vaibhav's PR gets merged, need to remove the set up of plio analytics from integration test step in ci.yml

2022-01-27 05:31 UTC, dalmia commented on src/pages/Dashboard.vue
> +        "Plio Num Questions Answered": this.plioMetrics["average_num_answered"] || 0,
directly show computed value here.

2022-01-27 09:12 UTC, merged