Style :  Explanation added in babel.config.js
avantifellows/plio-frontend pull request #63
Opened 2021-02-28 09:42 UTC by kavita1999

2021-03-01 16:42 UTC, pritamps requested changes

2021-03-01 16:42 UTC, pritamps commented on README.md
> +It includes features for:-
Why the `-`? It's not necessary.

2021-03-01 16:42 UTC, pritamps commented on babel.config.js
> +//You will require babel plugin to remove the console.log from production build.
Reword to `The babel plugin is needed to remove the console.log from production builds.`

2021-04-13 18:00 UTC, deepansh96 commented
Closing this!
We're now using a vue linter locally installed in our VSCode and also using pre-commit to check for common styling mistakes.

2021-04-13 18:00 UTC, closed without merging