add editor to input options
avantifellows/plio-frontend pull request #633
Opened 2022-02-24 05:51 UTC by Manyakalra3

## Summary
- Added quilljsEditor to input options.

## Test Plan

- [ ] Test Responsiveness
   - [ ] Laptop (1200px)
   - [ ] Tablet (760px)
   - [ ] Phone (320px)
- [ ] Cross-Browser Testing
   - [ ] Chrome
   - [ ] Firefox
   - [ ] Safari (use BrowserStack)
- [ ] ~Local Language Support~
- [ ] Hygiene and Housekeeping
   - [ ] Self-review
   - [ ] Comments have been added appropriately
   - [ ] Check for bundle size [here](https://bundlephobia.com/) if adding a package
   - [ ] Added relevant details like Labels/Projects/Milestones etc.
   - [ ] ~If adding or removing any environment variable:~
       - [ ] update `docs/ENV.md`
       - [ ] update Github Workflow files
       - [ ] update DockerFile
       - [ ] update the secrets for staging and production
- [ ] Testing
   - [ ] Wrote tests
   - [ ] Tested locally
   - [ ] Tested on staging
   - [ ] Tested on an actual physical phone
   - [ ] Tested on production
- [ ] ~Lighthouse Checks~
   - [ ] Images have `alt` attributes
   - [ ] Any `<img>` tags have `width` and `height` specified
   - [ ] Any `target="_blank"` links have `rel="noopener"`
   - [ ] Only SVGs are used as images. If PNGs are used, their size has been optimised.
   - [ ] Any SVGs without text have their `aria-label` attributes set

2022-02-25 10:02 UTC, deepansh96 commented
- In the question textbox and option textboxes, when we have formatting enabled, the formatting toolbar's top right and left edges are not rounded and that's why when selecting the textbox, you can see that you get this weird corner here.

https://user-images.githubusercontent.com/20169829/155678490-d7ae9a23-e759-46d1-820d-2d497ad1ed3b.mov

<hr>

- The placeholder's positioning is not correct in textboxes. In the question textbox, the placeholder is way towards the right, and the cursor starts from the very left. In the case of option textboxes, the placeholder is left of where the cursor starts

https://user-images.githubusercontent.com/20169829/155678851-6e0afb0d-3494-4a1a-8c48-61d5df6d7429.mov

<hr>

- By default, when there's nothing written in the question textbox, there is currently a small scrollbar. Which is not ideal because it gives the illusion that there is something to see whereas there is nothing. So a scrollbar should only appear when there is actually some content that exceeds the area of the textbox.

<img width="1302" alt="Screenshot 2022-02-25 at 1 44 17 PM" src="https://user-images.githubusercontent.com/20169829/155679510-4730f944-2d53-46ca-889a-477e046863a6.png">

<hr>

- Why this extra space is there at the bottom of all the textboxes?
![image](https://user-images.githubusercontent.com/20169829/155680329-b15326c0-e457-4fe8-9d01-ed8b8adfd7e2.png)

<hr>

- I think there's some fundamental bug with the implementation. Because when I'm typing, if I press Ctrl + B (to activate bold mode), and I start typing, something weird happens, you can see in the video below. This thing happens only if I press Ctrl + B/I/U and start typing. This DOES NOT happen for any other case, if I click the Bold/Italics/Underline icons, everything works flawlessly. Didn't you test it properly? You should test all the edge cases. If you don't, I'm anyway going to find it :P

https://user-images.githubusercontent.com/20169829/155693875-0b720924-dc49-4b4c-97f5-e6715cc488a8.mov

<hr>

- In the below video, I followed these steps. Clicked into the textbox -> Pressed "ctrl + B" on my keyboard -> I expected to see the Bold icon light up but it didn't. Same with the italics and underline. It's not that the bold mode or italics mode is not getting activated. It gets activated, but it's not visible on the icon. If I type any key on my keyboard after pressing "ctrl + B", it gets bold. Ideal behaviour should be -> Pressed Ctrl+B -> Bold icon gets lighted up.

https://user-images.githubusercontent.com/20169829/155695410-55ef4029-7c51-4bdf-ace0-4c8fc6c0069f.mov

<hr>

2022-03-01 17:06 UTC, deepansh96 requested changes

2022-03-01 17:06 UTC, deepansh96 commented on src/components/UI/Text/InputText.vue
> +      this.quillEditor.on("text-change", () => this.updateChange());
The name of this method can be improved. 
The name of the method should also reflect what it does. This method emits the current value of the textbox. So try naming it similar to that

2022-03-01 17:06 UTC, deepansh96 commented on src/components/UI/Text/InputText.vue
> +</style>
*to discuss*

2022-03-01 17:06 UTC, deepansh96 commented on src/components/UI/Text/Textarea.vue
> -        :class="[inputAreaClass, boxStyling]"
You removed the `inputAreaClass` and `boxStyling` class?

2022-03-01 17:06 UTC, deepansh96 commented on src/components/UI/Text/Textarea.vue
>      //update HTML on input change in textarea
same comments as in `InputText.vue` component.
- write a proper docstring, using syntax `/** ... */`
- write what this method is exactly doing

2022-03-01 17:06 UTC, deepansh96 commented on src/components/UI/Text/Textarea.vue
> +      //invoked on input changeconsole.
Be a little more descriptive
Write proper sentences
`this method is invoked the user types in the input box`

Also, re-verify for typos before sending the PR for review! There's a small typo here

2022-03-01 17:06 UTC, deepansh96 commented on src/components/UI/Text/Textarea.vue
> +
```suggestion
```

2022-03-01 17:06 UTC, deepansh96 commented on src/components/UI/Text/Textarea.vue
> +      placeholder: this.placeholder, //placeholder for textarea
no need of comment here

2022-03-01 17:06 UTC, deepansh96 commented on src/pages/Editor.vue
> +      this.reRender(); //for rerendering itemEditor whenever option is deleted.
```suggestion
      this.reRender(); // rerendering itemEditor whenever option is deleted.
```

2022-03-02 06:52 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +      class="rounded textbox flex relative mt-1 items-center"
will move it to textarea.vue.

2022-03-02 06:56 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +          name="placeholder"
This was actually part of the original code, we are passing props here,since it is a div now ,i will remove the unnecessary code.

2022-03-02 06:57 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +import "quill/dist/quill.snow.css";
okayyy

2022-03-02 06:57 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +        editor: null,
I will add comment here

2022-03-02 06:58 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +    // invoked on change in input
Got it ,will make the changes

2022-03-02 06:59 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +        this.quillEditor.getText() ? this.quillEditor.root.innerHTML : "" //return the formatted value
Yes,you asked this before,It is here just for handling any extra edge cases .should i remove it?

2022-03-02 09:46 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +      }
done

2022-03-02 09:47 UTC, Manyakalra3 commented on src/components/UI/Text/InputText.vue
> +    //new instance of quilljs is created
done

2022-03-14 10:41 UTC, deepansh96 commented on src/components/UI/Text/InputText.vue
> +    <div :class="containerStyleClass">
Refactor this file according to the changes made in Textarea.vue

2022-03-15 12:25 UTC, deepansh96 requested changes

2022-03-15 12:25 UTC, deepansh96 commented on src/components/UI/Text/Textarea.vue
> +        this.quillEditorElement.style.height = `${this.maxFHeightLimit}px`;
You didn't test this? Because it should've given an error

2023-04-07 05:47 UTC, closed without merging